### ISSUE TITLE
Visitor is seeing the pizzas

### ISSUE THREAD

**Issue by quintanilhar** [quintanilhar/pizzashop-java#1]
In order to be able to order a Pizza, as a Visitor, I want to see the pizzas menu available in the shop.

## Acceptance Criteria 

- [ ] A pizza should contain a name, a picture and a price
- [ ] Only active pizzas should be displayed 
- [ ] The pizzas should be listed in the alphabetical order by name

## Tasks 

- #4 
- #5
